#!/bin/bash
/home/s/sbush/programs/ont-guppy-cpu/bin/guppy_barcoder -i /t1-data/project/pregcare/sbush/MinION1/3.all_ont_fq -s /t1-data/project/pregcare/sbush/MinION1/4.demultiplexed_fq --barcode_kits EXP-PBC001 --compress_fastq --records_per_fastq 0 -t 10
/home/s/sbush/programs/ont-guppy-cpu/bin/guppy_barcoder -i /t1-data/project/pregcare/sbush/MinION2/3.all_ont_fq -s /t1-data/project/pregcare/sbush/MinION2/4.demultiplexed_fq --barcode_kits EXP-PBC001 --compress_fastq --records_per_fastq 0 -t 10
/home/s/sbush/programs/ont-guppy-cpu/bin/guppy_barcoder -i /t1-data/project/pregcare/sbush/MinION3/3.all_ont_fq -s /t1-data/project/pregcare/sbush/MinION3/4.demultiplexed_fq --barcode_kits EXP-PBC001 --compress_fastq --records_per_fastq 0 -t 10
/home/s/sbush/programs/ont-guppy-cpu/bin/guppy_barcoder -i /t1-data/project/pregcare/sbush/MinION4/3.all_ont_fq -s /t1-data/project/pregcare/sbush/MinION4/4.demultiplexed_fq --barcode_kits EXP-PBC001 --compress_fastq --records_per_fastq 0 -t 10
/home/s/sbush/programs/ont-guppy-cpu/bin/guppy_barcoder -i /t1-data/project/pregcare/sbush/MinION5/3.all_ont_fq -s /t1-data/project/pregcare/sbush/MinION5/4.demultiplexed_fq --barcode_kits EXP-PBC001 --compress_fastq --records_per_fastq 0 -t 10
/home/s/sbush/programs/ont-guppy-cpu/bin/guppy_barcoder -i /t1-data/project/pregcare/sbush/MinION6/3.all_ont_fq -s /t1-data/project/pregcare/sbush/MinION6/4.demultiplexed_fq --barcode_kits EXP-PBC001 --compress_fastq --records_per_fastq 0 -t 10
/home/s/sbush/programs/ont-guppy-cpu/bin/guppy_barcoder -i /t1-data/project/pregcare/sbush/MinION7/3.all_ont_fq -s /t1-data/project/pregcare/sbush/MinION7/4.demultiplexed_fq --barcode_kits EXP-PBC001 --compress_fastq --records_per_fastq 0 -t 10
/home/s/sbush/programs/ont-guppy-cpu/bin/guppy_barcoder -i /t1-data/project/pregcare/sbush/MinION8/3.all_ont_fq -s /t1-data/project/pregcare/sbush/MinION8/4.demultiplexed_fq --barcode_kits EXP-PBC001 --compress_fastq --records_per_fastq 0 -t 10
